[metadata]
author = "treymouledoux"
description = "Prompts for two nine-bit numbers and computes unsigned quotient and remainder, rejecting division by zero."
version = "1.0.0"
show_metadata = false
min_grid9_ver = "2026.1.0"

[config]
advanced_preprocess = true
dont_cache = false
echo_grid_mod = false
no_log = true
verbosity = 0
