[metadata]
author = "treymouledoux"
description = "Prints out the character for the GLYPH that you give it."
version = "1.0.2"
show_metadata = true
min_grid9_ver = "2026.1.0"

[config]
advanced_parse = true
dont_cache = false
echo_grid_mod = false
no_log = false
verbosity = 1