[metadata]
author = "treymouledoux"
description = "Prints a random character then another one and then the first one again."
version = "1.0.1"
show_metadata = true
min_grid9_ver = "2026.1.0"

[config]
advanced_parse = true
dont_cache = false
echo_grid_mod = false
no_log = false
verbosity = 1